import type { NextPage } from 'next'
import Head from 'next/head'
import VidHeader from '../components/vidHeader'

const Home: NextPage = () => {
  return (
    <div className='
      flex items-center justify-center
      min-h-screen min-w-full
      text-zinc-300 '>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <VidHeader /> 

    </div>
  )
}

export default Home
